language: go

sudo: required
dist: xenial

go:
  - 1.14
  - 1.15
  - tip

cache: apt

addons:
  apt:
    packages:
      - gobject-introspection
      - gtk-doc-tools
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - libwebp-dev
      - libwebpmux1

before_install:
  - wget https://github.com/jcupitt/libvips/archive/master.zip
  - unzip master
  - cd libvips-master
  - ./autogen.sh
  - >
    CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0
    ./configure
    --disable-debug
    --disable-dependency-tracking
    --disable-introspection
    --disable-static
    --enable-gtk-doc-html=no
    --enable-gtk-doc=no
    --enable-pyvips8=no
    --without-orc
    --without-python
    $1
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..

before_script:
  - go build -o bin/iiif cmd/iiif.go

script:
  - test `gofmt -s -d cmd iiif | tee -a /dev/fd/2 | wc -l` -eq 0
  - test `golint github.com/greut/iiif/iiif | tee -a /dev/fd/2 | wc -l` -eq 0
  - go vet .
  - >
    go test -v -race
    -covermode=atomic
    -coverprofile=coverage.out
    github.com/greut/iiif/iiif

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci
