// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iiif/image.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	iiif/image.proto

It has these top-level messages:
	CacheableImage
*/
package iiif

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CacheableImage struct {
	ModTime []byte `protobuf:"bytes,1,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	ETag    []byte `protobuf:"bytes,2,opt,name=e_tag,json=eTag,proto3" json:"e_tag,omitempty"`
	Buffer  []byte `protobuf:"bytes,3,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (m *CacheableImage) Reset()                    { *m = CacheableImage{} }
func (m *CacheableImage) String() string            { return proto.CompactTextString(m) }
func (*CacheableImage) ProtoMessage()               {}
func (*CacheableImage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CacheableImage) GetModTime() []byte {
	if m != nil {
		return m.ModTime
	}
	return nil
}

func (m *CacheableImage) GetETag() []byte {
	if m != nil {
		return m.ETag
	}
	return nil
}

func (m *CacheableImage) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func init() {
	proto.RegisterType((*CacheableImage)(nil), "main.CacheableImage")
}

func init() { proto.RegisterFile("iiif/image.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0xcc, 0xcc, 0x4c,
	0xd3, 0xcf, 0xcc, 0x4d, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d,
	0xcc, 0xcc, 0x53, 0x8a, 0xe0, 0xe2, 0x73, 0x4e, 0x4c, 0xce, 0x48, 0x4d, 0x4c, 0xca, 0x49, 0xf5,
	0x04, 0xc9, 0x0a, 0x49, 0x72, 0x71, 0xe4, 0xe6, 0xa7, 0xc4, 0x97, 0x64, 0xe6, 0xa6, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0xf0, 0x04, 0xb1, 0xe7, 0xe6, 0xa7, 0x84, 0x64, 0xe6, 0xa6, 0x0a, 0x09, 0x73,
	0xb1, 0xa6, 0xc6, 0x97, 0x24, 0xa6, 0x4b, 0x30, 0x81, 0xc5, 0x59, 0x52, 0x43, 0x12, 0xd3, 0x85,
	0xc4, 0xb8, 0xd8, 0x92, 0x4a, 0xd3, 0xd2, 0x52, 0x8b, 0x24, 0x98, 0xc1, 0xa2, 0x50, 0x5e, 0x12,
	0x1b, 0xd8, 0x1a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x02, 0xea, 0xe2, 0x7a, 0x00,
	0x00, 0x00,
}
